stages:
  - build

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

build:
  stage: build
  only:
    - master
  script:
    - cd root/front-end/kanban
    - npm install
    - npm run build
  tags: 
    - vue
